# Generated by Django 6.0.8 on 2026-08-31 08:22

from django.conf import settings
from django.db import migrations

from common.constants import PLATFORM_REVENUE_ACCOUNT_ID

PLATFORM_SYSTEM_USER_EMAIL = "platform-system@internal.ledgerplatform"


def create_platform_revenue_account(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    Account = apps.get_model("ledger", "Account")

    # get_or_create makes this migration safe to re-run and safe against
    # partial-failure re-application — it should never create a duplicate
    # system user or a duplicate platform account.
    system_user, _ = User.objects.get_or_create(
        email=PLATFORM_SYSTEM_USER_EMAIL,
        defaults={"is_active": True, "role": "admin"},
    )
    # Historical model instances from migrations don't have access to the
    # real manager methods like set_unusable_password() — set the field
    # directly via the underlying hasher's sentinel value instead.
    if not system_user.password:
        system_user.password = "!"  # Django's convention for "no usable password"
        system_user.save()

    Account.objects.get_or_create(
        id=PLATFORM_REVENUE_ACCOUNT_ID,
        defaults={
            "owner": system_user,
            "name": "platform_revenue",
            "currency": "USD",
            "allows_overdraft": False,
            "is_active": True,
        },
    )


def remove_platform_revenue_account(apps, schema_editor):
    Account = apps.get_model("ledger", "Account")
    Account.objects.filter(id=PLATFORM_REVENUE_ACCOUNT_ID).delete()
    # Deliberately NOT deleting the system user on reverse — it may be
    # referenced by historical LedgerEntry rows (on_delete=PROTECT would
    # block it anyway), and reversing this migration shouldn't risk data loss.


class Migration(migrations.Migration):
    dependencies = [
        ("ledger", "0001_initial"),  # adjust to your actual latest ledger migration
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            create_platform_revenue_account,
            reverse_code=remove_platform_revenue_account,
        ),
    ]
