# Generated by Django 6.0.8 on 2026-09-02 08:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_create_platform_revenue_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cached_balance',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=19),
        ),
    ]
