# Generated by Django 6.0.8 on 2026-09-03 17:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_account_cached_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceDiscrepancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cached_balance_at_check', models.DecimalField(decimal_places=4, max_digits=19)),
                ('derived_balance_at_check', models.DecimalField(decimal_places=4, max_digits=19)),
                ('discrepancy_amount', models.DecimalField(decimal_places=4, max_digits=19)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balance_discrepancies', to='ledger.account')),
            ],
        ),
    ]
